### ISSUE TITLE
Retrofit + Jackson?

### ISSUE THREAD

**Issue by FireMasterK** [rimthekid/LibreTube#3]
Would it be a better idea to use Retrofit with Jackson instead of directly using OkHttp?

This way you can just copy the server files from https://github.com/TeamPiped/Piped-Backend/tree/master/src/main/java/me/kavin/piped/utils/obj

**Comment by rimthekid** [comment]
Retrofit min API is 21 I'm supporting till API 19

**Comment by FireMasterK** [comment]
I would be against that since the current OkHttp version at https://github.com/rimthekid/LibreTube/blob/d7f6eb3f2982e60f42a6f0990308440bf76aab54/app/build.gradle#L45 doesn't support API 19

Also, NewPipe would be dropping API 19 at the end of this year to upgrade to OkHttp 4 (most likely, there's a discussion soon)

**Comment by FireMasterK** [comment]
https://code.cash.app/okhttp-3-13-requires-android-5

From the blog:

> Should we encounter any severe bugs or security problems we’ll backport the fixes and release. We plan to maintain this branch through December 31, 2020.

It's pretty much in maintenance mode.

**Comment by rimthekid** [comment]
Hmm that's it then I'll be migrating to retrofit with jackson thanks

**Comment by rimthekid** [comment]
which Jackson version should I use?

**Comment by rimthekid** [comment]
I'm using 2.13

**Comment by FireMasterK** [comment]
That's the same version used in the backend, it's always kept up-to-date via dependabot.

**Comment by rimthekid** [comment]
should I convert the objects to Kotlin I was thinking not to

**Comment by FireMasterK** [comment]
It will require a few changes to work anyways in it's current stage, so it would make sense to convert it to Kotlin and make those changes there.

**Comment by rimthekid** [comment]
So it was a bit of hassle but it's done now
